# BUILD SERVER
- name: Configure build server
  hosts: n4
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Java 8
      apt:
        name: openjdk-8-jdk
        state: present

    - name: Install Maven
      apt:
        name: maven
        state: present

     

#NEXUS SERVER
- name: Install Nexus Repository Manager 
  hosts: n5
  become: yes
  vars:
    nexus_version: "2.14.18-01"  
    nexus_download_url: "https://download.sonatype.com/nexus/oss/nexus-{{ nexus_version }}-bundle.tar.gz"  
    nexus_install_dir: "/opt/nexus-{{ nexus_version }}"
    nexus_data_dir: "/opt/sonatype-work"
    nexus_service_file: "/etc/systemd/system/nexus.service"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Java
      apt:
        name: openjdk-8-jdk
        state: present

    - name: Install required packages
      apt:
        name:
          - wget
          - tar
        state: present

    - name: Create Nexus install directory
      file:
        path: "{{ nexus_install_dir }}"
        state: directory
        mode: '0755'

    - name: Download Nexus tarball
      get_url:
        url: "{{ nexus_download_url }}"
        dest: "/tmp/nexus-{{ nexus_version }}-bundle.tar.gz"

    - name: Extract Nexus tarball
      unarchive:
        src: "/tmp/nexus-{{ nexus_version }}-bundle.tar.gz"
        dest: "/opt"
        remote_src: yes

    - name: Create Nexus data directory
      file:
        path: "{{ nexus_data_dir }}"
        state: directory
        mode: '0755'

    - name: Create Nexus user
      user:
        name: nexus
        system: yes
        shell: /sbin/nologin

    - name: Set ownership of Nexus directories
      file:
        path: "{{ item }}"
        owner: nexus
        group: nexus
        recurse: yes
      loop:
        - "{{ nexus_install_dir }}"
        - "{{ nexus_data_dir }}"

    - name: Configure Nexus to run as Nexus user
      lineinfile:
        path: "{{ nexus_install_dir }}/conf/nexus.properties"
        line: "nexus-work={{ nexus_data_dir }}"
        create: yes

    - name: Create Nexus systemd service file
      copy:
        dest: "{{ nexus_service_file }}"
        content: |
          [Unit]
          Description=Nexus Repository Manager
          After=network.target

          [Service]
          Type=forking
          User=nexus
          Group=nexus
          ExecStart={{ nexus_install_dir }}/bin/nexus start
          ExecStop={{ nexus_install_dir }}/bin/nexus stop
          Restart=on-failure
          LimitNOFILE=65536
          LimitNPROC=2048
          LimitMEMLOCK=infinity

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd configuration
      systemd:
        daemon_reload: yes

    - name: Start Nexus service
      systemd:
        name: nexus
        state: started
        enabled: yes

    - name: Clean up tarball
      file:
        path: "/tmp/nexus-{{ nexus_version }}-bundle.tar.gz"
        state: absent


# DEPLOY SERVERS
- name: Configure deploy servers
  hosts: deploy
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Java JDK
      apt:
        name: openjdk-8-jdk
        state: present

    - name: Download Apache Tomcat
      get_url:
        url: https://archive.apache.org/dist/tomcat/tomcat-7/v7.0.94/bin/apache-tomcat-7.0.94.tar.gz
        dest: /opt/tomcat.tar.gz

    - name: Extract Apache Tomcat
      unarchive:
        src: /opt/tomcat.tar.gz
        dest: /opt
        remote_src: yes

    - name: Create symbolic link for Tomcat
      file:
        src: /opt/apache-tomcat-7.0.94
        dest: /opt/tomcat
        state: link

    - name: Create Tomcat user and set ownership
      user:
        name: tomcat
        state: present
        shell: /bin/false

    - name: Set ownership for Tomcat
      file:
        path: /opt/tomcat
        state: directory
        owner: tomcat
        group: tomcat
        recurse: yes

    - name: Ensure correct permissions on Tomcat scripts
      file:
        path: "{{ item }}"
        mode: '0755'
        owner: tomcat
        group: tomcat
      loop:
        - /opt/tomcat/bin/startup.sh
        - /opt/tomcat/bin/shutdown.sh

    - name: Create Tomcat systemd service file
      copy:
        dest: /etc/systemd/system/tomcat.service
        content: |
          [Unit]
          Description=Apache Tomcat Web Application Container
          After=network.target

          [Service]
          Type=forking
          User=tomcat
          Group=tomcat
          Environment="JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64"
          Environment="CATALINA_PID=/opt/tomcat/temp/tomcat.pid"
          Environment="CATALINA_HOME=/opt/tomcat"
          Environment="CATALINA_BASE=/opt/tomcat"
          Environment="CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC"
          Environment="JAVA_OPTS=-Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom"
          ExecStart=/opt/tomcat/bin/startup.sh
          ExecStop=/opt/tomcat/bin/shutdown.sh
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Start and enable Tomcat service
      systemd:
        name: tomcat
        enabled: yes
        state: started

    - name: Remove the downloaded Tomcat tar.gz
      file:
        path: /opt/tomcat.tar.gz
        state: absent
