# BUILD SERVER
- name: Configure build server
  hosts: n4
  become: true

  tasks: 
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Java
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Install Maven 
      apt:
        name: maven
        state: present

# NEXUS SERVER
name: Configure Nexus server 
  hosts: n5
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Java 
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Create Nexus User
      user:
        name: nexus
        state: present
        shell: /bin/bash
        create_home: yes

    - name: Download Nexus
      get_url:
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /opt/nexus.tar.gz

    - name: Extract Nexus
      unarchive:
        src: /opt/nexus.tar.gz
        dest: /opt
        remote_src: yes

    - name: Set ownership for Nexus directories
      file:
        path: /opt/nexus-3.37.3-02
        state: directory
        owner: nexus
        group: nexus
        recurse: yes

    # Ensure the directory exists before attempting to modify it
    - name: Check if nexus.rc file exists
      stat:
        path: /opt/nexus-3.37.3-02/bin/nexus.rc
      register: nexus_rc

    - name: Set Nexus RUN_AS_USER in nexus.rc
      lineinfile:
        path: /opt/nexus-3.37.3-02/bin/nexus.rc
        regexp: '^#RUN_AS_USER='
        line: 'RUN_AS_USER=nexus'
        state: present
      when: nexus_rc.stat.exists

    - name: Set Nexus as a service
      copy:
        dest: /etc/systemd/system/nexus.service
        content: |
          [Unit]
          Description=nexus service
          After=network.target

          [Service]
          Type=forking
          User=nexus
          ExecStart=/opt/nexus-3.37.3-02/bin/nexus start
          ExecStop=/opt/nexus-3.37.3-02/bin/nexus stop
          Restart=on-abort

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Enable and start Nexus service
      systemd:
        name: nexus
        enabled: yes
        state: started

# DEPLOY SERVERS
- hosts: deploy
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
     
    - name: Install Java JDK
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Download Apache Tomcat
      get_url:
        url: https://downloads.apache.org/tomcat/tomcat-9/v9.0.65/bin/apache-tomcat-9.0.65.tar.gz
        dest: /opt/tomcat.tar.gz

    - name: Extract Apache Tomcat
      unarchive:
        src: /opt/tomcat.tar.gz
        dest: /opt
        remote_src: yes

    - name: Create symbolic link for Tomcat
      file:
        src: /opt/apache-tomcat-9.0.65
        dest: /opt/tomcat
        state: link

    - name: Create Tomcat user and set ownership
      user:
        name: tomcat
        state: present
        shell: /bin/false

    - name: Set ownership for Tomcat
      file:
        path: /opt/tomcat
        state: directory
        owner: tomcat
        group: tomcat
        recurse: yes

    - name: Start Tomcat service
      shell: "/opt/tomcat/bin/startup.sh"
      args:
        chdir: /opt/tomcat/
