# BUILD SERVER
- name: Configure build server
  hosts: n4
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Java
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Install Maven
      apt:
        name: maven
        state: present

# NEXUS SERVER
- name: Deploy and Configure Nexus
  hosts: n5
  become: yes
  tasks:
    # Existing setup tasks
    - name: Create Nexus user
      ansible.builtin.user:
        name: nexus
        state: present

    - name: Download Nexus
      ansible.builtin.get_url:
        url: "https://download.sonatype.com/nexus/professional-bundle/nexus-professional-2.15.1-02-bundle.tar.gz"
        dest: /tmp/nexus.tar.gz

    - name: Extract Nexus
      ansible.builtin.unarchive:
        src: /tmp/nexus.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Create symbolic link to Nexus
      ansible.builtin.file:
        src: /opt/nexus-<version>
        dest: /opt/nexus
        state: link

    - name: Ensure nexus user owns the Nexus directory
      ansible.builtin.file:
        path: /opt/nexus
        owner: nexus
        group: nexus
        recurse: yes

    - name: Set Nexus as a service
      ansible.builtin.template:
        src: nexus.service.j2
        dest: /etc/systemd/system/nexus.service
      notify: Reload systemd

    # New tasks for troubleshooting and validation
    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: yes
      when: ansible_facts['ansible_systemd'] is defined

    - name: Start Nexus service
      ansible.builtin.systemd:
        name: nexus
        state: started
        enabled: yes
      register: nexus_service_status
      failed_when: nexus_service_status.failed

    - name: Check Nexus service status
      ansible.builtin.command:
        cmd: systemctl status nexus.service
      register: nexus_status
      failed_when: nexus_status.rc != 0
      ignore_errors: yes

    - name: Fetch Nexus service logs
      ansible.builtin.command:
        cmd: journalctl -xeu nexus.service
      register: nexus_logs
      failed_when: nexus_logs.rc != 0
      ignore_errors: yes

    - name: Debug Nexus service status
      ansible.builtin.debug:
        msg: "{{ nexus_status.stdout }}"

    - name: Debug Nexus service logs
      ansible.builtin.debug:
        msg: "{{ nexus_logs.stdout }}"

  handlers:
    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: yes


# DEPLOY SERVERS
- name: Configure deploy servers
  hosts: deploy
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Java JDK
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Download Apache Tomcat
      get_url:
        url: https://downloads.apache.org/tomcat/tomcat-9/v9.0.74/bin/apache-tomcat-9.0.74.tar.gz
        dest: /opt/tomcat.tar.gz

    - name: Extract Apache Tomcat
      unarchive:
        src: /opt/tomcat.tar.gz
        dest: /opt
        remote_src: yes

    - name: Create symbolic link for Tomcat
      file:
        src: /opt/apache-tomcat-9.0.74
        dest: /opt/tomcat
        state: link

    - name: Create Tomcat user and set ownership
      user:
        name: tomcat
        state: present
        shell: /bin/false

    - name: Set ownership for Tomcat
      file:
        path: /opt/tomcat
        state: directory
        owner: tomcat
        group: tomcat
        recurse: yes

    - name: Start Tomcat service
      shell: "/opt/tomcat/bin/startup.sh"
      args:
        chdir: /opt/tomcat/
