---
- name: Upload artifact to Nexus Repository from Build Server
  hosts: n4
  become: yes

  vars:
    nexus_url: "http://3.90.1.192:8081/nexus"  
    repository: "releases"
    group_id: "com.web.cal"
    artifact_id: "WebAppCal"
    packaging: "war"
    nexus_username: "admin"
    nexus_password: "admin123"
    artifact_path: "/home/ubuntu/workspace/ansible-project/target"
  
  tasks:
    - name: Get version from pom.xml
      command: mvn help:evaluate -Dexpression=project.version -q -DforceStdout
      args:
        chdir: /home/ubuntu/workspace/ansible-project
      register: mvn_version_output
    
    - name: Set artifact version
      set_fact:
        artifact_version: "{{ mvn_version_output.stdout.strip() }}"

    - name: Print artifact version
      debug:
        msg: "Artifact version is: {{ artifact_version }}"

    - name: Check if the WAR file exists
      stat:
        path: "{{ artifact_path }}/WebAppCal-{{ artifact_version }}.war"
      register: war_file_check

    - name: Fail if the WAR file does not exist
      fail:
        msg: "WAR file not found: {{ artifact_path }}/WebAppCal-{{ artifact_version }}.war"
      when: not war_file_check.stat.exists

    - name: Upload artifact to Nexus
      uri:
        url: "{{ nexus_url }}/content/repositories/{{ repository }}/{{ group_id | replace('.', '/') }}/{{ artifact_id }}/{{ artifact_version }}/{{ artifact_id }}-{{ artifact_version }}.{{ packaging }}"
        method: PUT
        user: "{{ nexus_username }}"
        password: "{{ nexus_password }}"
        force_basic_auth: yes
        body_format: raw
        body: "{{ lookup('file', artifact_path + '/WebAppCal-' + artifact_version + '.war') }}"
        headers:
          Content-Type: application/octet-stream
        status_code: 201
      when: war_file_check.stat.exists
