---
- name: Deploy Maven artifact to Nexus
  hosts: n4
  gather_facts: yes
  tasks:
    - name: Install Maven (if not already installed)
      become: yes
      apt:
        name: maven
        state: present

    - name: Ensure Maven project is up-to-date
      command: mvn clean install
      args:
        chdir: /home/ubuntu/workspace/ansible-project

    - name: Deploy artifact to Nexus using Maven
      command: mvn deploy
      args:
        chdir: /home/ubuntu/workspace/ansible-project
      environment:
        MAVEN_OPTS: "-Dusername=admin -Dpassword=admin123"
