---
- hosts: n4
  become: yes
  vars:
    nexus_username: "admin"
    nexus_password: "admin123"
    nexus_url: "http://{{ hostvars['n5'].ansible_host }}:8081"
    repository_name: "maven-releases"  # Ensure this matches your Nexus repository name
  tasks:
    - name: Read the Maven version
      shell: "mvn help:evaluate -Dexpression=project.version -q -DforceStdout"
      args:
        chdir: /home/ubuntu/workspace/ansible-project
      register: maven_version

    - name: Set the version as a fact
      set_fact:
        version: "{{ maven_version.stdout.strip() }}"

    - name: Debug the file path
      debug:
        msg: "File path: /home/ubuntu/workspace/ansible-project/target/WebAppCal-{{ version }}.war"

    - name: Check if the file exists
      stat:
        path: "/home/ubuntu/workspace/ansible-project/target/WebAppCal-{{ version }}.war"
      register: file_stat

    - name: Fail if the file does not exist
      fail:
        msg: "The file does not exist at the specified path: /home/ubuntu/workspace/ansible-project/target/WebAppCal-{{ version }}.war"
      when: not file_stat.stat.exists

    - name: Read the WAR file content
      slurp:
        src: "/home/ubuntu/workspace/ansible-project/target/WebAppCal-{{ version }}.war"
      register: war_file

    - name: Upload WAR to Nexus
      uri:
        url: "{{ nexus_url }}/repository/{{ repository_name }}/com/web/cal/WebAppCal/{{ version }}/WebAppCal-{{ version }}.war"
        method: PUT
        user: "{{ nexus_username }}"
        password: "{{ nexus_password }}"
        force_basic_auth: yes
        body_format: raw
        body: "{{ war_file.content | b64decode }}"
        status_code: 201
        return_content: yes
      register: response

    - name: Debug response from Nexus
      debug:
        var: response

    - name: Ensure successful upload
      assert:
        that:
          - response.status == 201
        fail_msg: "Upload failed: {{ response.status }} - {{ response.msg }}"
        success_msg: "Upload successful"
