---
- hosts: n4
  become: yes
  vars:
    nexus_username: "admin"
    nexus_password: "admin123"
    nexus_url: "http://{{ hostvars['n5'].ansible_host }}:8081"
    repository_name: "maven-releases"  # Ensure this matches your Nexus repository name
  tasks:
    - name: Read the Maven version
      shell: "mvn help:evaluate -Dexpression=project.version -q -DforceStdout"
      args:
        chdir: /home/ubuntu/workspace/ansible-project
      register: maven_version

    - name: Set the version as a fact
      set_fact:
        version: "{{ maven_version.stdout.strip() }}"

    - name: Debug the URL for uploading
      debug:
        msg: "{{ nexus_url }}/repository/{{ repository_name }}/com/web/cal/WebAppCal/{{ version }}/WebAppCal-{{ version }}.war"

    - name: Upload WAR to Nexus
      uri:
        url: "{{ nexus_url }}/repository/{{ repository_name }}/com/web/cal/WebAppCal/{{ version }}/WebAppCal-{{ version }}.war"
        method: PUT  # Use PUT for Maven artifact uploads
        user: "{{ nexus_username }}"
        password: "{{ nexus_password }}"
        force_basic_auth: yes
        body_format: raw  # Use raw for binary data
        body: "{{ lookup('file', playbook_dir + '/target/WebAppCal-' + version + '.war') }}"
        status_code: 201
        return_content: yes
      register: response

    - name: Debug response from Nexus
      debug:
        var: response

    - name: Ensure successful upload
      assert:
        that:
          - response.status == 201
        fail_msg: "Upload failed: {{ response.status }} - {{ response.msg }}"
        success_msg: "Upload successful"
