---
- name: Deploy WAR file from Nexus to Tomcat
  hosts: deploy
  vars:
    nexus_url: "http://34.201.66.66:8081/nexus"
    repo_id: "releases"
    group_id: "com.web.cal"
    artifact_id: "WebAppCal"
    tomcat_home: "/opt/tomcat"
    deploy_dir: "{{ tomcat_home }}/webapps"
    backup_dir: "/tmp/backup"

  tasks:
    - name: Get metadata from Nexus
      uri:
        url: "{{ nexus_url }}/service/local/repositories/{{ repo_id }}/content/{{ group_id | replace('.', '/') }}/{{ artifact_id }}/maven-metadata.xml"
        method: GET
        return_content: yes
      register: metadata_response
      failed_when: metadata_response.status != 200

    - name: Extract latest version from metadata
      xml:
        xmlstring: "{{ metadata_response.content }}"
        xpath: "/metadata/versioning/latest"
        content: text
      register: latest_version

    - name: Set version based on metadata
      set_fact:
        version: "{{ latest_version.matches[0] }}"

    - name: Create backup directory if not exists
      file:
        path: "{{ backup_dir }}"
        state: directory

    - name: Backup existing WAR file if it exists
      copy:
        src: "{{ deploy_dir }}/{{ artifact_id }}-{{ version }}.war"
        dest: "{{ backup_dir }}/{{ artifact_id }}-{{ version }}.war.{{ ansible_date_time.date }}_{{ ansible_date_time.time }}"
      ignore_errors: yes

    - name: Download WAR file from Nexus
      get_url:
        url: "{{ nexus_url }}/service/local/artifact/maven/content?r={{ repo_id }}&g={{ group_id }}&a={{ artifact_id }}&v={{ version }}&p=war"
        dest: "/tmp/{{ artifact_id }}-{{ version }}.war"
        mode: '0644'

    - name: Stop Tomcat service
      service:
        name: tomcat
        state: stopped

    - name: Deploy WAR file to Tomcat
      copy:
        src: "/tmp/{{ artifact_id }}-{{ version }}.war"
        dest: "{{ deploy_dir }}/"
        owner: tomcat
        group: tomcat
        mode: '0644'

    - name: Start Tomcat service
      service:
        name: tomcat
        state: started

    - name: Clean up downloaded WAR file
      file:
        path: "/tmp/{{ artifact_id }}-{{ version }}.war"
        state: absent
