---
- name: Deploy WAR file from Nexus to Tomcat
  hosts: deploy
  vars:
    nexus_url: "http://34.201.66.66:8081/nexus"
    repo_id: "releases"
    group_id: "com.web.cal"
    artifact_id: "WebAppCal"
    version: "0.0.6"  # Update this as needed or implement dynamic version fetching
    tomcat_home: "/opt/tomcat"
    deploy_dir: "{{ tomcat_home }}/webapps"
    backup_dir: "/tmp/backup"

  tasks:
  
    - name: Download WAR file from Nexus
      get_url:
        url: "{{ nexus_url }}/content/repositories/releases/{{ group_id | replace('.', '/') }}/{{ artifact_id }}/{{ version }}/{{ artifact_id }}-{{ version }}.war"
        dest: "/tmp/{{ artifact_id }}-{{ version }}.war"
        mode: '0644'

    - name: Deploy WAR file to Tomcat
      copy:
        src: "/tmp/{{ artifact_id }}-{{ version }}.war"
        dest: "{{ deploy_dir }}/{{ artifact_id }}.war"
        owner: tomcat
        group: tomcat
        mode: '0644'

    - name: Restart Tomcat service
      service:
        name: tomcat
        state: restarted

    - name: Clean up downloaded WAR file
      file:
        path: "/tmp/{{ artifact_id }}-{{ version }}.war"
        state: absent
