---
- name: Deploy application
  hosts: deploy
  become: yes
  vars:
    artifact_url: "http://18.205.103.243:8081/nexus/content/repositories/releases/com/web/cal/WebAppCal/0.0.6/WebAppCal-0.0.6.war"
    tomcat_webapps_dir: "/opt/tomcat/webapps"
    local_artifact_path: "{{ tomcat_webapps_dir }}/WebAppCal-0.0.6.war"

  tasks:
    - name: Download artifact from Nexus
      get_url:
        url: "{{ artifact_url }}"
        dest: "{{ local_artifact_path }}"
        mode: '0644'

    - name: Ensure Tomcat webapps directory exists
      file:
        path: "{{ tomcat_webapps_dir }}"
        state: directory

    - name: Restart Tomcat to deploy the new WAR
      service:
        name: tomcat
        state: restarted

    