---
- name: Fetch the version from the build server
  hosts: n4
  become: yes
  tasks:
    - name: Read version from file
      slurp:
        src: /tmp/version.txt
      register: version_file_content

    - name: Set version fact
      set_fact:
        version: "{{ version_file_content.content | b64decode | trim }}"

    - name: Save version fact for use in deploy
      local_action:
        module=copy
        content="{{ version }}"
        dest="/tmp/version.txt"

- name: Deploy the WAR to the deploy servers
  hosts: deploy
  become: yes
  vars:
    nexus_url: "3.90.1.192:8081/nexus"  # Replace with your Nexus URL

  tasks:
    - name: Fetch version from local file
      local_action:
        module=fetch
        src=/tmp/version.txt
        dest=/tmp/version.txt
        flat=yes

    - name: Set version from fetched file
      set_fact:
        version: "{{ lookup('file', '/tmp/version.txt') | trim }}"

    - name: Debug version
      debug:
        msg: "Artifact version is: {{ version }}"

    - name: Download WAR from Nexus
      get_url:
        url: "http://{{ nexus_url }}/repository/releases/com/web/cal/WebAppCal/{{ version }}/WebAppCal-{{ version }}.war"
        dest: "/opt/tomcat/webapps/WebAppCal.war"
        force: yes  # Overwrite the file if it already exists

    - name: Stop Tomcat service
      shell: "/opt/tomcat/bin/shutdown.sh"
      args:
        chdir: /opt/tomcat/

    - name: Start Tomcat service
      shell: "/opt/tomcat/bin/startup.sh"
      args:
        chdir: /opt/tomcat/
