---
- name: Deploy WAR file from Nexus to Tomcat
  hosts: deploy
  vars:
    nexus_url: "http://34.201.66.66:8081/nexus"
    repo_id: "releases"
    group_id: "com.web.cal"
    artifact_id: "WebAppCal"
    war_file: "{{ artifact_id }}-{{ version }}.war"
    tomcat_home: "/opt/tomcat"
    deploy_dir: "{{ tomcat_home }}/webapps"
    backup_dir: "/tmp/backup"

  tasks:
    - name: Get latest version of the artifact from Nexus
      uri:
        url: "{{ nexus_url }}/service/local/artifact/maven/resolve?r={{ repo_id }}&g={{ group_id }}&a={{ artifact_id }}&v=LATEST"
        method: GET
        return_content: yes
        status_code: 200
      register: nexus_response

    - name: Set version based on Nexus response
      set_fact:
        version: "{{ nexus_response.json.data.version }}"

    - name: Create backup directory if not exists
      file:
        path: "{{ backup_dir }}"
        state: directory

    - name: Backup existing WAR file if it exists
      copy:
        src: "{{ deploy_dir }}/{{ war_file }}"
        dest: "{{ backup_dir }}/{{ war_file }}.{{ ansible_date_time.date }}_{{ ansible_date_time.time }}"
      ignore_errors: yes

    - name: Download WAR file from Nexus
      get_url:
        url: "{{ nexus_url }}/service/local/artifact/maven/content?r={{ repo_id }}&g={{ group_id }}&a={{ artifact_id }}&v={{ version }}&p=war"
        dest: "/tmp/{{ war_file }}"
        mode: '0644'

    - name: Stop Tomcat service
      service:
        name: tomcat
        state: stopped

    - name: Deploy WAR file to Tomcat
      copy:
        src: "/tmp/{{ war_file }}"
        dest: "{{ deploy_dir }}/"
        owner: tomcat
        group: tomcat
        mode: '0644'

    - name: Start Tomcat service
      service:
        name: tomcat
        state: started

    - name: Clean up downloaded WAR file
      file:
        path: "/tmp/{{ war_file }}"
        state: absent
